CREATE TABLE Users (
    id NUMBER(38) CONSTRAINT USER_NN_ID NOT NULL,
    username VARCHAR(30) CONSTRAINT USER_NN_USERNAME NOT NULL,
    creationDate timestamp DEFAULT sysdate CONSTRAINT USER_NN_CREATIONDATE NOT NULL,
    firstName varchar(100) CONSTRAINT USER_NN_FIRSTNAME NOT NULL,
    lastName VARCHAR(100) CONSTRAINT USER_NN_LASTNAME NOT NULL,
    middleName VARCHAR(50) CONSTRAINT USER_NN_MIDDLENAME NOT NULL,
    password VARCHAR(255) DEFAULT 'JOOKIE' CONSTRAINT USER_NN_PASSWORD NOT NULL,
    CONSTRAINT USER_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX USER_IDX_PKEY on Users(id))
) TABLESPACE GLOSSARY_DATA;

CREATE INDEX USER_IDX_USER ON Users (username);
CREATE INDEX USER_IDX_NAME ON Users (firstName,lastName);
CREATE INDEX USER_IDX_E_NAME ON Users (lastName,firstName);

CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1 CACHE 100; 

INSERT INTO Users (id,username,firstName,lastName,middleName) VALUES (user_seq.nextVal,'alandry','Aaron','Landry','Leigh');

CREATE TABLE Terms (
    id NUMBER(38) CONSTRAINT TERM_NN_ID NOT NULL,
    userID NUMBER(38) CONSTRAINT TERM_NN_USER NOT NULL,
    creationDate timestamp DEFAULT sysdate CONSTRAINT TERM_NN_CREATIONDATE NOT NULL,
    name varchar(100) CONSTRAINT TERM_NN_NAME NOT NULL,
    definition varchar(4000) CONSTRAINT TERM_NN_DEFINITION NOT NULL,
    sdate_date NUMBER(38),
    sdate_epoch NUMBER(5), 
    CONSTRAINT TERM_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX TERM_IDX_PKEY on Terms(id)),
    CONSTRAINT TERM_FKEY_USER FOREIGN KEY(userID) REFERENCES Users(id)
) TABLESPACE GLOSSARY_DATA;

CREATE INDEX TERM_IDX_USER ON Terms (userID);
CREATE INDEX TERM_IDX_NAME ON Terms (name);
CREATE INDEX TERM_IDX_E_CDATE ON Terms (creationDate);
CREATE INDEX TERM_IDX_E_SDATE1 ON Terms (sdate_epoch,sdate_date);
CREATE INDEX TERM_IDX_E_SDATE2 ON Terms (sdate_date,sdate_epoch);

CREATE SEQUENCE term_seq START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE TABLE Categories (
    id NUMBER(38) CONSTRAINT CAT_NN_ID NOT NULL,
    parentID NUMBER(38),
    userID NUMBER(38) CONSTRAINT CAT_NN_USER NOT NULL,
    creationDate timestamp DEFAULT sysdate CONSTRAINT CAT_NN_CREATIONDATE NOT NULL,
    indent NUMBER(5) DEFAULT 0 CONSTRAINT CAT_NN_INDENT NOT NULL,
    name varchar(100) CONSTRAINT CAT_NN_NAME NOT NULL,
    longName varchar(1000) DEFAULT '' CONSTRAINT CAT_NN_LONGNAME NOT NULL,
    CONSTRAINT CAT_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX CAT_IDX_PKEY on Categories(id)),
    CONSTRAINT CAT_FKEY_PARENT FOREIGN KEY(parentID) REFERENCES Categories(id),
    CONSTRAINT CAT_FKEY_USER FOREIGN KEY(userID) REFERENCES Users(id)
) TABLESPACE GLOSSARY_DATA;

CREATE INDEX CAT_IDX_USER ON Categories (userID);
CREATE INDEX CAT_IDX_NAME ON Categories (name);
CREATE INDEX CAT_IDX_CDATE ON Categories (creationDate);
CREATE INDEX CAT_IDX_PARENT ON Categories (parentID);
CREATE INDEX CAT_IDX_PARENT_NAME ON Categories (parentID,name);
CREATE INDEX CAT_IDX_IND ON Categories (indent);
CREATE INDEX CAT_IDX_IND_NAME ON Categories (indent,name);

CREATE SEQUENCE cat_seq START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE TABLE TermCategoryLinks(
	id NUMBER(38) CONSTRAINT TERMCAT_LINK_NN_ID NOT NULL,
	termID NUMBER(38) CONSTRAINT TERMCAT_LINK_NN_TERM NOT NULL,
	categoryID NUMBER(38) CONSTRAINT TERMCAT_LINK_NN_CAT NOT NULL,
	CONSTRAINT TERMCAT_LINK_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX TERMCAT_LINK_IDX_PKEY on TermCategoryLinks(id)),
	CONSTRAINT TERMCAT_LINK_FKEY_TERM FOREIGN KEY(termID) REFERENCES Terms(id),
	CONSTRAINT TERMCAT_LINK_FKEY_CAT FOREIGN KEY(categoryID) REFERENCES Categories(id),
        CONSTRAINT TERMCAT_LINK_UNQ UNIQUE (termID,categoryID) USING INDEX (CREATE INDEX TERMCAT_LINK_IDX_TERM_CAT ON TermCategoryLinks(termID,categoryID))
) TABLESPACE GLOSSARY_DATA;
CREATE INDEX TERMCAT_LINK_IDX_CAT_TERM ON TermCategoryLinks (categoryID,termID);

CREATE SEQUENCE termcat_link_seq START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE OR REPLACE TRIGGER termcat_link_ai BEFORE INSERT ON TermCategoryLinks FOR EACH ROW
BEGIN
    :new.id := termcat_link_seq.NEXTVAL;
END;
/

CREATE TABLE Novels (
    id NUMBER(38) CONSTRAINT NOVEL_NN_ID NOT NULL,
    ordinal NUMBER(4) CONSTRAINT NOVEL_NN_ORD NOT NULL,
    userID NUMBER(38) CONSTRAINT NOVEL_NN_USER NOT NULL,
    creationDate timestamp DEFAULT sysdate CONSTRAINT NOVEL_NN_CREATIONDATE NOT NULL,
    name varchar(100) CONSTRAINT NOVEL_NN_NAME NOT NULL,
    CONSTRAINT NOVEL_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX NOVEL_IDX_PKEY on Novels(id)),
    CONSTRAINT NOVEL_FKEY_USER FOREIGN KEY(userID) REFERENCES Users(id)
) TABLESPACE GLOSSARY_DATA;

CREATE INDEX NOVEL_IDX_USER ON Novels (userID);
CREATE INDEX NOVEL_IDX_NAME ON Novels (name);
CREATE INDEX NOVEL_IDX_CDATE ON Novels (creationDate);
CREATE INDEX NOVEL_IDX_PARENT ON Novels (ordinal);
CREATE INDEX NOVEL_IDX_PARENT_NAME ON Novels (ordinal,name);

CREATE SEQUENCE novel_seq START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE TABLE TermNovelLinks(
	id NUMBER(38) CONSTRAINT TERMNOVEL_LINK_NN_ID NOT NULL,
	termID NUMBER(38) CONSTRAINT TERMNOVEL_LINK_NN_TERM NOT NULL,
	novelID NUMBER(38) CONSTRAINT TERMNOVEL_LINK_NN_NOVEL NOT NULL,
	CONSTRAINT TERMNOVEL_LINK_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX TERMNOVEL_LINK_IDX_PKEY on TermNovelLinks(id)),
	CONSTRAINT TERMNOVEL_LINK_FKEY_TERM FOREIGN KEY(termID) REFERENCES Terms(id),
	CONSTRAINT TERMNOVEL_LINK_FKEY_NOVEL FOREIGN KEY(novelID) REFERENCES Novels(id),
        CONSTRAINT TERMNOVEL_LINK_UNQ UNIQUE (termID,novelID) USING INDEX (CREATE INDEX TERMNOVEL_LINK_IDX_TERM_NOVEL ON TermNovelLinks(termID,novelID))
) TABLESPACE GLOSSARY_DATA;
CREATE INDEX TERMNOVEL_LINK_IDX_NOVEL_TERM ON TermNovelLinks (novelID,termID);

CREATE SEQUENCE termnovel_link_seq START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE OR REPLACE TRIGGER termnovel_link_ai BEFORE INSERT ON TermNovelLinks FOR EACH ROW
BEGIN
    :new.id := termnovel_link_seq.NEXTVAL;
END;
/

INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,1,'(Superiad) The Shores of Gor''Nahara');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,2,'(Superiad) The Twiceborn');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,3,'(Superiad) The Mephitic Blood');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,4,'(Superiad) In the Wake of Dragons');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,5,'(Superiad) The Thread of Ages');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,6,'(Superiad) The Land of the Dawn');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,7,'(Superiad) The Blood of Tytans');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,8,'(Superiad) Blades of Flesh');
INSERT INTO Novels (id,userID,ordinal,name) VALUES (novel_seq.nextVal,1,9,'(Superiad) The Dawn''s Son');


CREATE TABLE TermAllCategoryLinks(
	id NUMBER(38) CONSTRAINT TERMALLCAT_LINK_NN_ID NOT NULL,
	termID NUMBER(38) CONSTRAINT TERMALLCAT_LINK_NN_TERM NOT NULL,
	categoryID NUMBER(38) CONSTRAINT TERMALLCAT_LINK_NN_CAT NOT NULL,
	CONSTRAINT TERMALLCAT_LINK_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX TERMALLCAT_LINK_IDX_PKEY on TermAllCategoryLinks(id)),
	CONSTRAINT TERMALLCAT_LINK_FKEY_TERM FOREIGN KEY(termID) REFERENCES Terms(id),
	CONSTRAINT TERMALLCAT_LINK_FKEY_CAT FOREIGN KEY(categoryID) REFERENCES Categories(id),
        CONSTRAINT TERMALLCAT_LINK_UNQ UNIQUE (termID,categoryID) USING INDEX (CREATE INDEX TERMALLCAT_LINK_IDX_TERM_CAT ON TermAllCategoryLinks(termID,categoryID))
) TABLESPACE GLOSSARY_DATA;
CREATE INDEX TERMALLCAT_LINK_IDX_CAT_TERM ON TermAllCategoryLinks (categoryID,termID);

CREATE SEQUENCE termallcat_link_seq START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE OR REPLACE TRIGGER termallcat_link_ai BEFORE INSERT ON TermAllCategoryLinks FOR EACH ROW
BEGIN
    :new.id := termallcat_link_seq.NEXTVAL;
END;
/

CREATE TABLE CategoryAllChildrenLinks(
	id NUMBER(38) CONSTRAINT CATALLCAT_LINK_NN_ID NOT NULL,
	parentID NUMBER(38) CONSTRAINT CATALLCAT_LINK_NN_PARENT NOT NULL,
	childID NUMBER(38) CONSTRAINT CATALLCAT_LINK_NN_CHILD NOT NULL,
	CONSTRAINT CATALLCAT_LINK_PKEY PRIMARY KEY (id) USING INDEX (CREATE INDEX CATALLCAT_LINK_IDX_PKEY on CategoryAllChildrenLinks(id)),
	CONSTRAINT CATALLCAT_LINK_FKEY_PARENT FOREIGN KEY(parentID) REFERENCES Categories(id),
	CONSTRAINT CATALLCAT_LINK_FKEY_CHILD FOREIGN KEY(childID) REFERENCES Categories(id),
        CONSTRAINT CATALLCAT_LINK_UNQ UNIQUE (parentID,childID) USING INDEX (CREATE INDEX CATALLCAT_LINK_IDX_P_CHILD ON CategoryAllChildrenLinks(parentID,childID))
) TABLESPACE GLOSSARY_DATA;
CREATE INDEX CATALLCAT_LINK_IDX_CHILD_P ON CategoryAllChildrenLinks (childID,parentID);

CREATE SEQUENCE catallcat_link_seq START WITH 1 INCREMENT BY 1 CACHE 100;

CREATE OR REPLACE TRIGGER catallcat_link_ai BEFORE INSERT ON CategoryAllChildrenLinks FOR EACH ROW
BEGIN
    :new.id := catallcat_link_seq.NEXTVAL;
END;
/

ALTER TABLE Terms ADD parsedDefinition CLOB;

ALTER TABLE Terms add matchLowercase NUMBER(1) DEFAULT 0 CONSTRAINT TERM_NN_MATCHLC NOT NULL;

ALTER TABLE Terms add isYencari NUMBER(1) DEFAULT 0 CONSTRAINT TERM_NN_ISYENCARI NOT NULL;
ALTER TABLE Terms add firstYencourName VARCHAR(100);
ALTER TABLE Terms add secondYencourName VARCHAR(100);
ALTER TABLE Terms add thirdYencourName VARCHAR(100);
ALTER TABLE Terms add firstAegeaName VARCHAR(100);
ALTER TABLE Terms add secondAegeaBirthName VARCHAR(100);
ALTER TABLE Terms add secondAegeaUniversityName VARCHAR(100);
ALTER TABLE Terms add secondAegeaGreatWarName VARCHAR(100);
ALTER TABLE Terms add sargarathName VARCHAR(100);
ALTER TABLE Terms add aYencariName VARCHAR(100);
ALTER TABLE Terms add superiName VARCHAR(100);
ALTER TABLE Terms add modernName VARCHAR(100);
ALTER TABLE Terms add chara VARCHAR(500);
ALTER TABLE Terms add marg VARCHAR(200);