
CREATE BIGFILE TABLESPACE GLOSSARY_DATA
  DATAFILE 'C:\APP\DBORACLE\ORADATA\GLOSSARY_DATA.DBF'
    SIZE 10M
    AUTOEXTEND ON;

CREATE TABLESPACE GLOSSARY_IDX
  DATAFILE 'C:\APP\DBORACLE\ORADATA\GLOSSARY_IDX.dat' 
    SIZE 10M
    REUSE
    AUTOEXTEND ON NEXT 10M MAXSIZE 500M;


